name: codeEducation-fc-challenge-ci-sonar-cloud
on:
  pull_request:
    branches:
      - develop
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0          
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.17

      - name: Install dependencies
        run: npm install

      - name: Gather Test Coverage
        run: npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}